name: 'Publish Report per branch'
description: 'Publish HTML, Plot (csv) reports with trend history per branch'
author: 'mgrybyk'
branding:
  icon: 'layout'
  color: 'gray-dark'
inputs:
  report_id:
    description: 'Unique report id'
    required: true
    default: 'html-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  report_dir:
    description: 'Folder with generated html report or csv file(s)'
    required: true
  report_type:
    description: 'html or csv'
    required: false
    default: 'html'
  list_dirs:
    description: 'Write index.html to the Github Action folders. Might cause concurrency issues!'
    required: false
    default: false
outputs:
  # report_url and report_history_url have the same url for CSV reports
  report_url:
    description: 'Published Report url'
  report_history_url:
    description: 'Published History list url'
runs:
  using: 'node20'
  main: 'dist/index.js'
